/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ufpr.sistemapedidos.view;

import javax.swing.JOptionPane;
import org.ufpr.sistemapedidos.infra.ProdutoDAO;
import org.ufpr.sistemapedidos.model.Produto;
import org.ufpr.sistemapedidos.model.TableModelCliente;
import org.ufpr.sistemapedidos.model.TableModelProduto;

/**
 *
 * @author Programmer
 */
public class ProdutoF extends javax.swing.JFrame {
    ProdutoDAO dao = new ProdutoDAO();
    private TableModelProduto tableModelProduto;
    /**
     * Creates new form ProdutoJFrame
     */
    public ProdutoF() {
        initComponents();
        this.tableModelProduto = new TableModelProduto();
        this.jTableProduto.setModel(tableModelProduto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        produtoFechar = new javax.swing.JButton();
        produtoLimpar = new javax.swing.JButton();
        produtoSalvar = new javax.swing.JButton();
        produtoApagar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        produtoResposta = new javax.swing.JLabel();
        produtoBuscar = new javax.swing.JTextField();
        produtoCodigo = new javax.swing.JTextField();
        produtoDescricao = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProduto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de produtos");
        setAlwaysOnTop(true);

        jLabel1.setText("Codigo");

        jLabel2.setText("Descrição");

        produtoFechar.setText("Fechar");
        produtoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoFecharActionPerformed(evt);
            }
        });

        produtoLimpar.setText("Limpar");
        produtoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoLimparActionPerformed(evt);
            }
        });

        produtoSalvar.setText("Salvar");
        produtoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoSalvarActionPerformed(evt);
            }
        });

        produtoApagar.setText("Apagar");
        produtoApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoApagarActionPerformed(evt);
            }
        });

        jLabel3.setText("Procurar");

        produtoResposta.setForeground(new java.awt.Color(255, 0, 0));
        produtoResposta.setToolTipText("");

        produtoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoBuscarActionPerformed(evt);
            }
        });
        produtoBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                produtoBuscarKeyReleased(evt);
            }
        });

        produtoCodigo.setEnabled(false);

        jTableProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdutoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableProduto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(555, 555, 555)
                        .addComponent(produtoResposta, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(produtoBuscar)
                            .addComponent(produtoDescricao)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(produtoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(produtoSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(produtoApagar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(produtoLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(produtoFechar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(produtoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(produtoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(produtoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(produtoResposta, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(produtoFechar)
                    .addComponent(produtoLimpar)
                    .addComponent(produtoSalvar)
                    .addComponent(produtoApagar))
                .addGap(146, 146, 146))
        );

        setSize(new java.awt.Dimension(916, 508));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void produtoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoLimparActionPerformed
        limpar();
    }//GEN-LAST:event_produtoLimparActionPerformed

    private void produtoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_produtoFecharActionPerformed

    private void produtoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoSalvarActionPerformed
        String codigo = produtoCodigo.getText();
        String descricao = produtoDescricao.getText();
        if(validarCampos(descricao)){
            int code = (produtoCodigo.getText().equals("")) ? 0 : Integer.parseInt(produtoCodigo.getText());
            Produto produto = new Produto(code, descricao);
            String msg = dao.salvar(produto);
            produto = dao.getProduto(descricao);
            this.tableModelProduto.addProduto(produto);
            JOptionPane.showMessageDialog(this, msg);
            limpar();
        }else{
            JOptionPane.showMessageDialog(this, "Favor preencher os campos!");
        }
        

    }//GEN-LAST:event_produtoSalvarActionPerformed

    private void produtoApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoApagarActionPerformed
        String codigo = produtoCodigo.getText();
        String descricao = produtoDescricao.getText();
        if(validarCampos(codigo, descricao)){
            String msg = dao.excluir(produtoCodigo.getText());
            int linhaSelecionada = jTableProduto.getSelectedRow();
            this.tableModelProduto.removerProduto(linhaSelecionada);
            JOptionPane.showMessageDialog(this, msg);
            limpar();
        }else{
            JOptionPane.showMessageDialog(this, "Busque um cliente para deletar!");
        }

    }//GEN-LAST:event_produtoApagarActionPerformed

    private void produtoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoBuscarActionPerformed
       
    }//GEN-LAST:event_produtoBuscarActionPerformed

    private void produtoBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_produtoBuscarKeyReleased
        if(produtoBuscar.getText().length()==0){
            produtoResposta.setText("");
        }
        Produto produto = dao.getProduto(produtoBuscar.getText());
        if(produto != null){
            produtoResposta.setText("");
            produtoCodigo.setText(String.valueOf(produto.getId()));
            produtoDescricao.setText(produto.getDescricao());
        }else{
            if(produtoBuscar.getText().length()>1){
                produtoCodigo.setText("");
                produtoDescricao.setText("");
                produtoResposta.setText("Nenhum produto encontrado");
            }
            
        }
    }//GEN-LAST:event_produtoBuscarKeyReleased

    private void jTableProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdutoMouseClicked
        if(evt.getClickCount() == 1){
            int linhaSelecionada = jTableProduto.getSelectedRow();
            produtoCodigo.setText("" + jTableProduto.getValueAt(linhaSelecionada, 0));
            produtoDescricao.setText("" + jTableProduto.getValueAt(linhaSelecionada, 1));
        }
    }//GEN-LAST:event_jTableProdutoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutoF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutoF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutoF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutoF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableProduto;
    private javax.swing.JButton produtoApagar;
    private javax.swing.JTextField produtoBuscar;
    private javax.swing.JTextField produtoCodigo;
    private javax.swing.JTextField produtoDescricao;
    private javax.swing.JButton produtoFechar;
    private javax.swing.JButton produtoLimpar;
    private javax.swing.JLabel produtoResposta;
    private javax.swing.JButton produtoSalvar;
    // End of variables declaration//GEN-END:variables

    private void limpar() {
        produtoBuscar.setText("");
        produtoCodigo.setText("");
        produtoDescricao.setText("");
        produtoBuscar.requestFocus();
    }

    private boolean validarCampos(String descricao) {
        return descricao.length()>0 && descricao.length()<=45;
    }
    private boolean validarCampos(String codigo, String descricao) {
        return codigo.length()>0 && (descricao.length()>0 && descricao.length()<=45);
    }
}
